baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My Personal Website'
theme = 'austere'

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 2
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'